In [ ]:
# Import all necessary libaries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load data into pandas
df = pd.read_csv('/content/Expresso_churn_dataset.csv')
df.head()

,user_id,REGION,TENURE,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,MRG,REGULARITY,TOP_PACK,FREQ_TOP_PACK,CHURN
0,00000bfd7d50f01092811bc0c8d7b0d6fe7c3596,FATICK,K > 24 month,4250.0,15.0,4251.0,1417.0,17.0,4.0,388.0,46.0,1.0,1.0,2.0,NO,54.0,On net 200F=Unlimited _call24H,8.0,0.0
1,00000cb4a5d760de88fecb38e2f71b7bec52e834,NaN,I 18-21 month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,4.0,NaN,NaN,1.0
2,00001654a9d9f96303d9969d0a4a851714a4bb57,NaN,K > 24 month,3600.0,2.0,1020.0,340.0,2.0,NaN,90.0,46.0,7.0,NaN,NaN,NO,17.0,On-net 1000F=10MilF;10d,1.0,0.0
3,00001dd6fa45f7ba044bd5d84937be464ce78ac2,DAKAR,K > 24 month,13500.0,15.0,13502.0,4501.0,18.0,43804.0,41.0,102.0,2.0,NaN,NaN,NO,62.0,"Data:1000F=5GB,7d",11.0,0.0
4,000028d9e13a595abe061f9b58f3d76ab907850f,DAKAR,K > 24 month,1000.0,1.0,985.0,328.0,1.0,NaN,39.0,24.0,NaN,NaN,NaN,NO,11.0,Mixt 250F=Unlimited_call24H,2.0,0.0

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87123 entries, 0 to 87122
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   user_id         87123 non-null  object
 1   REGION          52818 non-null  object
 2   TENURE          87122 non-null  object
 3   MONTANT         56578 non-null  float64
 4   FREQUENCE_RECH  56578 non-null  float64
 5   REVENUE         57780 non-null  float64
 6   ARPU_SEGMENT    57780 non-null  float64
 7   FREQUENCE       57780 non-null  float64
 8   DATA_VOLUME     44426 non-null  float64
 9   ON_NET          55422 non-null  float64
 10  ORANGE          50936 non-null  float64
 11  TIGO            35098 non-null  float64
 12  ZONE1           6949 non-null   float64
 13  ZONE2           5559 non-null   float64
 14  MRG             87122 non-null  object
 15  REGULARITY      87122 non-null  float64
 16  TOP_PACK        50742 non-null  object
 17  FREQ_TOP_PACK   50742 non-null  float64
 18  CHURN           87122 non-null  float64
dtypes: float64(14), object(5)
memory usage: 12.6+ MB

In [ ]:
df.describe()

,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,REGULARITY,FREQ_TOP_PACK,CHURN
count,56578.000000,56578.000000,57780.000000,57780.000000,57780.000000,44426.000000,55422.000000,50936.000000,35098.000000,6949.000000,5559.000000,87122.000000,50742.000000,87122.000000
mean,5583.696437,11.651296,5556.987210,1852.333974,14.115819,3465.545829,283.192360,95.687019,23.361958,8.697942,7.529951,28.115482,9.342556,0.187794
std,7180.015716,13.369252,7202.253108,2400.746484,14.841825,14415.541556,883.991441,201.449105,64.565656,43.970821,28.913325,22.326339,12.165688,0.390550
min,50.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,1000.000000,2.000000,1000.000000,333.000000,3.000000,0.000000,5.000000,7.000000,2.000000,0.000000,0.000000,6.000000,2.000000,0.000000
50%,3000.000000,7.000000,3001.000000,1000.000000,9.000000,265.000000,27.000000,29.000000,6.000000,1.000000,2.000000,24.000000,5.000000,0.000000
75%,7500.000000,16.000000,7499.000000,2500.000000,20.000000,2897.750000,160.000000,98.000000,21.000000,4.000000,5.000000,51.000000,12.000000,0.000000
max,197400.000000,106.000000,147739.000000,49246.000000,91.000000,926547.000000,24281.000000,5841.000000,2899.000000,1469.000000,932.000000,62.000000,185.000000,1.000000

In [ ]:
df.shape

(87123, 19)

In [ ]:
# Handle Missing and corrupted values

df.isnull().sum()

user_id               0
REGION            34305
TENURE                1
MONTANT           30545
FREQUENCE_RECH    30545
REVENUE           29343
ARPU_SEGMENT      29343
FREQUENCE         29343
DATA_VOLUME       42697
ON_NET            31701
ORANGE            36187
TIGO              52025
ZONE1             80174
ZONE2             81564
MRG                   1
REGULARITY            1
TOP_PACK          36381
FREQ_TOP_PACK     36381
CHURN                 1
dtype: int64

In [ ]:
# Deal with missing values accross all columns using mode and fillna
for i in df.columns: # Loop through the dataframe columns
  if df[i].isna().sum() > 0: # Check for missing values in each columns,
    df[i].fillna(df[i].mode()[0], inplace=True) # If missing value in column, use mode to fill the missing values

df.isnull().sum() # All missing value cleared

user_id           0
REGION            0
TENURE            0
MONTANT           0
FREQUENCE_RECH    0
REVENUE           0
ARPU_SEGMENT      0
FREQUENCE         0
DATA_VOLUME       0
ON_NET            0
ORANGE            0
TIGO              0
ZONE1             0
ZONE2             0
MRG               0
REGULARITY        0
TOP_PACK          0
FREQ_TOP_PACK     0
CHURN             0
dtype: int64

In [ ]:
df.head()

,user_id,REGION,TENURE,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,MRG,REGULARITY,TOP_PACK,FREQ_TOP_PACK,CHURN
0,00000bfd7d50f01092811bc0c8d7b0d6fe7c3596,FATICK,K > 24 month,4250.0,15.0,4251.0,1417.0,17.0,4.0,388.0,46.0,1.0,1.0,2.0,NO,54.0,On net 200F=Unlimited _call24H,8.0,0.0
1,00000cb4a5d760de88fecb38e2f71b7bec52e834,DAKAR,I 18-21 month,500.0,1.0,500.0,167.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,NO,4.0,All-net 500F=2000F;5d,1.0,1.0
2,00001654a9d9f96303d9969d0a4a851714a4bb57,DAKAR,K > 24 month,3600.0,2.0,1020.0,340.0,2.0,0.0,90.0,46.0,7.0,0.0,0.0,NO,17.0,On-net 1000F=10MilF;10d,1.0,0.0
3,00001dd6fa45f7ba044bd5d84937be464ce78ac2,DAKAR,K > 24 month,13500.0,15.0,13502.0,4501.0,18.0,43804.0,41.0,102.0,2.0,0.0,0.0,NO,62.0,"Data:1000F=5GB,7d",11.0,0.0
4,000028d9e13a595abe061f9b58f3d76ab907850f,DAKAR,K > 24 month,1000.0,1.0,985.0,328.0,1.0,0.0,39.0,24.0,1.0,0.0,0.0,NO,11.0,Mixt 250F=Unlimited_call24H,2.0,0.0

In [ ]:
df.MRG.value_counts() # Using value count check for the values and how many times they appeared in the column

MRG
NO    87123
Name: count, dtype: int64

In [ ]:
df.REGION.value_counts()

REGION
DAKAR          55074
THIES           7294
SAINT-LOUIS     4813
LOUGA           4127
KAOLACK         3872
DIOURBEL        2722
TAMBACOUNDA     2164
KAFFRINE        1815
FATICK          1508
KOLDA           1507
MATAM           1167
ZIGUINCHOR       900
SEDHIOU          117
KEDOUGOU          42
M                  1
Name: count, dtype: int64

In [ ]:
df.TOP_PACK.value_counts()

TOP_PACK
All-net 500F=2000F;5d             49025
On net 200F=Unlimited _call24H     6239
Data:490F=1GB,7d                   4667
Data: 100 F=40MB,24H               3586
Mixt 250F=Unlimited_call24H        2869
                                  ...
APANews_weekly                        1
FIFA_TS_weekly                        1
EVC_JOKKO30                           1
EVC_Jokko_Weekly                      1
FIFA_TS_daily                         1
Name: count, Length: 92, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87123 entries, 0 to 87122
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   user_id         87123 non-null  object
 1   REGION          87123 non-null  object
 2   TENURE          87123 non-null  object
 3   MONTANT         87123 non-null  float64
 4   FREQUENCE_RECH  87123 non-null  float64
 5   REVENUE         87123 non-null  float64
 6   ARPU_SEGMENT    87123 non-null  float64
 7   FREQUENCE       87123 non-null  float64
 8   DATA_VOLUME     87123 non-null  float64
 9   ON_NET          87123 non-null  float64
 10  ORANGE          87123 non-null  float64
 11  TIGO            87123 non-null  float64
 12  ZONE1           87123 non-null  float64
 13  ZONE2           87123 non-null  float64
 14  MRG             87123 non-null  object
 15  REGULARITY      87123 non-null  float64
 16  TOP_PACK        87123 non-null  object
 17  FREQ_TOP_PACK   87123 non-null  float64
 18  CHURN           87123 non-null  float64
dtypes: float64(14), object(5)
memory usage: 12.6+ MB

In [ ]:
# Using Label Encoding, change categorical data to numerical data
from sklearn.preprocessing import LabelEncoder # Import package label encoder
le = LabelEncoder()
col = [1, 2, 16] # COlumn index that are categorical data
for i in df.columns:
  if df[i].dtypes() == 'object':# Loop through the index
    df.iloc[:, i] = le.fit_transform(df.iloc[:, i]) # Fit and transform the column

df.head() # Show the data after label encoding

,user_id,REGION,TENURE,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,MRG,REGULARITY,TOP_PACK,FREQ_TOP_PACK,CHURN
0,00000bfd7d50f01092811bc0c8d7b0d6fe7c3596,2,7,4250.0,15.0,4251.0,1417.0,17.0,4.0,388.0,46.0,1.0,1.0,2.0,NO,54.0,67,8.0,0.0
1,00000cb4a5d760de88fecb38e2f71b7bec52e834,0,5,500.0,1.0,500.0,167.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,NO,4.0,10,1.0,1.0
2,00001654a9d9f96303d9969d0a4a851714a4bb57,0,7,3600.0,2.0,1020.0,340.0,2.0,0.0,90.0,46.0,7.0,0.0,0.0,NO,17.0,68,1.0,0.0
3,00001dd6fa45f7ba044bd5d84937be464ce78ac2,0,7,13500.0,15.0,13502.0,4501.0,18.0,43804.0,41.0,102.0,2.0,0.0,0.0,NO,62.0,19,11.0,0.0
4,000028d9e13a595abe061f9b58f3d76ab907850f,0,7,1000.0,1.0,985.0,328.0,1.0,0.0,39.0,24.0,1.0,0.0,0.0,NO,11.0,62,2.0,0.0

In [ ]:
X = df.drop(['MRG', 'user_id', 'CHURN'], axis=1) # Drop the columns that are not needed, and the target column as well
X.head()

,REGION,TENURE,MONTANT,FREQUENCE_RECH,REVENUE,ARPU_SEGMENT,FREQUENCE,DATA_VOLUME,ON_NET,ORANGE,TIGO,ZONE1,ZONE2,REGULARITY,TOP_PACK,FREQ_TOP_PACK
0,2,7,4250.0,15.0,4251.0,1417.0,17.0,4.0,388.0,46.0,1.0,1.0,2.0,54.0,67,8.0
1,0,5,500.0,1.0,500.0,167.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,4.0,10,1.0
2,0,7,3600.0,2.0,1020.0,340.0,2.0,0.0,90.0,46.0,7.0,0.0,0.0,17.0,68,1.0
3,0,7,13500.0,15.0,13502.0,4501.0,18.0,43804.0,41.0,102.0,2.0,0.0,0.0,62.0,19,11.0
4,0,7,1000.0,1.0,985.0,328.0,1.0,0.0,39.0,24.0,1.0,0.0,0.0,11.0,62,2.0

In [ ]:
# There are high variation in our data, and we would need to standardize it to ensure we have good accuracy for our model
from sklearn.preprocessing import StandardScaler # Import package for standard scaler
sc = StandardScaler() # Create object for standard scaler
X = sc.fit_transform(X) # Fit and transform the data
X # Show the data after standard scaler

array([[-0.2066911 ,  0.20819688,  0.07150698, ...,  1.15938878,
         1.90063152,  0.21084513],
       [-0.63603518, -2.79465668, -0.52620606, ..., -1.08012526,
        -0.62846139, -0.4784663 ],
       [-0.63603518,  0.20819688, -0.03209661, ..., -0.49785161,
         1.94500157, -0.4784663 ],
       ...,
       [ 2.1547013 ,  0.20819688, -0.53417557, ..., -0.13952936,
        -0.62846139, -0.4784663 ],
       [ 0.00798093,  0.20819688,  0.66922003, ...,  1.24896934,
         1.54567111,  0.70321044],
       [ 1.08134111,  0.20819688, -0.52620606, ..., -1.2144961 ,
        -0.62846139, -0.4784663 ]])

In [ ]:
y = df.CHURN.values # Get the target column
y # Show the target column

array([0., 1., 0., ..., 0., 0., 0.])

In [ ]:
from sklearn.model_selection import train_test_split # Import package for train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) # Split the data into train and test

In [ ]:
from sklearn.linear_model import LogisticRegression # Import package for logistic regression
model = LogisticRegression(random_state=0) # Create object for logistic regression
model.fit(X_train, y_train) # Fit the data to the model

LogisticRegression(random_state=0)

In [ ]:
pred = model.predict(X_test) # Predict the test data
pred # Show the prediction

array([0., 1., 0., ..., 1., 0., 0.])

In [ ]:
from sklearn.metrics import confusion_matrix # Import package for confusion matrix
cm = confusion_matrix(y_test, pred) # Create object for confusion matrix
cm # Show the confusion matrix

array([[12919,  1226],
       [ 1139,  2141]])

In [ ]:
from sklearn.metrics import classification_report # Import package for classification report
print(classification_report(y_test, pred)) # Show the classification report

              precision    recall  f1-score   support

         0.0       0.92      0.91      0.92     14145
         1.0       0.64      0.65      0.64      3280

    accuracy                           0.86     17425
   macro avg       0.78      0.78      0.78     17425
weighted avg       0.87      0.86      0.86     17425

In [ ]:
from sklearn.metrics import accuracy_score # Import package for accuracy score
print("Test Accuracy: ", accuracy_score(y_test, pred)) # Show the accuracy score for test data
print("Train Accuarcy: ", accuracy_score(y_train, model.predict(X_train))) # Show the accuracy score for train data

Test Accuracy:  0.8642754662840746
Train Accuarcy:  0.866466756578381

In [ ]:
!pip install pypickle # Install pypickle package for saving the model

Collecting pypickle
  Downloading pypickle-1.1.0-py3-none-any.whl (5.1 kB)
Installing collected packages: pypickle
Successfully installed pypickle-1.1.0

In [ ]:
import pypickle # Import package for saving the model
f = 'churn_model.pkl' # Create file name for saving the model
pypickle.save(f, model) # Save the model

[pypickle] Pickle file saved: [churn_model.pkl]

True